name: Scrape (Selenium) and Save Artifacts

on:
  # 02:00 IST daily == 20:30 UTC
  schedule:
    - cron: "30 20 * * *"
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # Install Chrome/Chromium on the runner
      - name: Install Google Chrome (pin major to avoid driver flaps)
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '141'   # change to 'stable' later if you wish

      # Remove any preinstalled chromedriver so Selenium Manager can pick the right one
      - name: Remove incompatible ChromeDriver from PATH
        run: |
          if command -v chromedriver; then
            echo "Removing preinstalled chromedriver at $(command -v chromedriver)"
            sudo rm -f "$(command -v chromedriver)"
          else
            echo "No chromedriver found on PATH; nothing to remove."
          fi

      - name: Show versions
        run: |
          python --version
          echo "Chrome path: ${{ steps.chrome.outputs.chrome-path }}"
          ${{ steps.chrome.outputs.chrome-path }} --version || true

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
          PYTHONUNBUFFERED: "1"
        run: |
          python -u scraper/scrape.py
          echo "Run complete"

      # ---- push JSON to your Wix endpoint ----
      - name: Push prices to Wix (Products)
        if: ${{ success() && hashFiles('data/scraped_data.json') != '' }}
        env:
          WEBHOOK_URL: ${{ secrets.WIX_PRODUCTS_WEBHOOK_URL }}   # https://whey2much.in/_functions/updateproducts
          WEBHOOK_TOKEN: ${{ secrets.WIX_PRODUCTS_TOKEN }}       # same as PRICES_WEBHOOK_TOKEN in Wix
        run: |
          set -euo pipefail
          if [ -z "${WEBHOOK_URL:-}" ] || [ -z "${WEBHOOK_TOKEN:-}" ]; then
            echo "❌ Missing secrets. Set WIX_PRODUCTS_WEBHOOK_URL and WIX_PRODUCTS_TOKEN in repo Secrets." >&2
            exit 1
          fi
          if [ ! -s data/scraped_data.json ]; then
            echo "❌ data/scraped_data.json not found or empty." >&2
            exit 1
          fi
          echo "Posting scraped_data.json to Wix..."
          curl -sS --fail-with-body -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "x-api-key: $WEBHOOK_TOKEN" \
            --data-binary @data/scraped_data.json
          echo "✅ Posted to Wix."

      - name: Upload results (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scrape-output
          path: |
            data/scraped_data.json
            data/scraped_data.csv
            data/debug/
          if-no-files-found: warn
